### ISSUE TITLE
Peer to Peer System and WebRTC

### ISSUE THREAD

**Issue by nb9960** [COPS-IITBHU/DevTalks#11]
**Abstract**

In this I'll be focusing on what is peer to peer system(with few examples) followed by how does WebRTC work in bit detail.

**Topics covered**

- Peer to peer systems over traditional client server network
- Example of peer to peer system
- What is WebRTC and how does it work?

        
**Expected Duration**

15 minutes

**Track**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**

None
        
**Resources**

[WebRTC basic](https://www.html5rocks.com/en/tutorials/webrtc/basics/)
You may search for demo projects to get an overview.

**Content**

PPT will be shared
    
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by nb9960** [comment]
Held on 20/09/2020

PPT: https://1drv.ms/p/s!Av06-L2JzgQegQ18eFOMWLMgOG9O?e=C5TGyM    
What is WebRTC and how it works: https://www.html5rocks.com/en/tutorials/webrtc/basics/    
Demo Apps for implementation: https://webrtc.github.io/samples/

**Comment by king-11** [comment]
Ohhhhh 🤯
