### ISSUE TITLE
DevOps: What and Why

### ISSUE THREAD

**Issue by shivanshs9** [COPS-IITBHU/DevTalks#12]
**Abstract**

DevOps is rising in trend yet it's the easily-misunderstood role. It's not a technical specialist field but rather a combination of a set of principles (inspired by Agile methodology) and tools to deliver applications and services at high velocity.

**Topics covered**

- What really is DevOps?
- What it isn't
- CI/CD
- Infrastructure as Code
- SRE V/S DevOps
        
**Expected Duration**

40 minutes

**Track**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Prerequisites**

Make sure to empty your mind of any pre-defined notions of what DevOps is.

**Resources**

- [AWS Blog](https://aws.amazon.com/devops/what-is-devops/)

**Content**

[Deck](https://pasteapp.com/p/sAhQLvbXPBi/s/RiWyZyx1oRN?view=5HfFmtUD6Jf)
    
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by shivanshs9** [comment]
Held on 20 September.

**Comment by nishantwrp** [comment]
Slides - https://pasteapp.com/p/sAhQLvbXPBi/s/RiWyZyx1oRN?view=5HfFmtUD6Jf
