### ISSUE TITLE
Aggregation Pipeline in MongoDB

### ISSUE THREAD

**Issue by cyborg7459** [COPS-IITBHU/DevTalks#13]
**Abstract**
This talk would be regarding aggregation pipeline, a framework for data aggregation modeled on the concept of data processing pipelines. We would cover the basics of it and would then apply it in a small project

**Topics covered**

* What are aggregation pipelines
* Stages
* Operators
* Analysing data using aggregation pipelines

**Expected Duration**

* 30-40 minutes

**Track**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**

* Knowledge of basic NodeJS and MongoDB

* Basic JavaScript (async-await, ES6) 

  

**Resources**

You can go through the documentation beforehand, although it is not necessary and basics would be covered

* https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline/
* https://docs.mongodb.com/manual/reference/operator/aggregation/

**Content**
PPT and the Project repository would be shared after meeting
    

---

### Note

The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by cyborg7459** [comment]
Talk given on 9 November 2020

**Comment by nishantwrp** [comment]
Slides -> https://docs.google.com/presentation/d/1ROelscGDXP1PfvF5Ujvefkt5ru_js0iuJTkaOpX7Zws/edit#slide=id.g9a48c6cda4_0_1070
