### ISSUE TITLE
Next Gen bundlers

### ISSUE THREAD

**Issue by king-11** [COPS-IITBHU/DevTalks#17]
**Abstract**
The time of webpack is long gone new bundlers with better DX experience have started popping.

**Topics covered**
- ESM
- WebPack
- Vite
        
**Expected Duration**
30 mins

**Track**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**
Knowledge about ES Modules and Bundlers
        
**Resources**

### Conference Video

- [Vite Rethinking Frontend Tooling](https://portal.gitnation.org/contents/vite-rethinking-frontend-tooling)

### Blogs

- [Comparing the new generation of build tools](https://css-tricks.com/comparing-the-new-generation-of-build-tools)
- [How it feels to learn javascript in 2016](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f)
- [Modern Javascript explained for dinosaurs](https://peterxjang.com/blog/modern-javascript-explained-for-dinosaurs.html)

### Podcasts

- [All About Vite with Evan You](https://shoptalkshow.com/454/)
- [Next Gen Bundlers with Jason Miller and Fred Schott](https://shoptalkshow.com/448/)

**Content**

https://www.canva.com/design/DAErqV8UPMg/wxc8p40cOLQTAJIT6Ce96Q/view
    
---
### Note
The time and venue will be decided in the Discord Server, so make sure you've joined up the Server.

**Comment by humblenginr** [comment]
> The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

Is it still valid considering we are using discord as primary means for communication now ?

**Comment by nishantwrp** [comment]
No, I don't believe it is. Feel free to make a PR updating the issue template :).

**Comment by humblenginr** [comment]
Ok, the template's already updated, since this issue is created before that update, it still has the old info.

**Comment by king-11** [comment]
Dev talk done on 3rd Oct 2021
