### ISSUE TITLE
UI and 3d models in website

### ISSUE THREAD

**Issue by yashrajbharti** [COPS-IITBHU/DevTalks#2]
**Abstract**
Will talk about Github, how to maintain a green streak or at least fill some greens, UI concepts, CSS tricks and some books and cool websites. Most talk will be about three.js and how to add 3D model scenes and perspective camera. 📷 

**Topics covered**
Github :octocat:  
UI
Important books 📖 
three.js
        
**Expected Duration**
30mins 

**Track**

- [ ] Beginner
- [x]  Intermediate
- [ ] Advanced

**Prerequisites**
Knowledge of frontend.
        
**Resources**
Books- 
burn your portfolio,
eloquent javascript,
the clean coder,
the missing manual,
pro mean stack
etc.

**Content**
 Talk will be about three.js and how to add 3D model scenes and perspective camera, ambient     lights, etc. Vectary.com . Some of my own GitHub links:
> [Dark UI](https://darkui.netlify.com)
> [UI slider](https://yashrajbharti.github.io/UI-slider)
> [Pokemon](https://yashrajbharti.github.io/Pokemon/)
> [Thanos Portal effect](https://portal-particle.netlify.com)   
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by shivanshs9** [comment]
Held on 08/09
