### ISSUE TITLE
[FlappyBird Web Game]Evolutionary Algorithms in gaming

### ISSUE THREAD

**Issue by nishantkr18** [COPS-IITBHU/DevTalks#3]
**Abstract**
What is more exciting than playing games? It's making them. And what is even cooler is to make machines play them for you! And what better an algorithm to use than the one that made us all, *The Genetic Algorithm*.

**Topics covered**
* Genetic Algorithms
* Object-Oriented Programming Style
* Why not to build everything from scratch!
* P5.js for fast Graphical prototyping
        
**Expected Duration**
 20 minutes

**Track**

- [x] Beginner
- [ ] Intermediate 
- [ ] Advanced

**Prerequisites**
* Basic Javascript programming.
        
**Resources**
* [P5.js](https://p5js.org/reference/)
* [Genetic Algorithm](https://www.youtube.com/watch?v=VnwjxityDLQ)

**Content**
* [link](https://nishantkr18.github.io/FlappyBirdOnJavascript/)
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by shivanshs9** [comment]
Held on 08/09
