### ISSUE TITLE
Three JS 

### ISSUE THREAD

**Issue by Anikaaasingh** [COPS-IITBHU/DevTalks#30]
**Abstract**

This talk will brief people about the basics, uses, importance and application of Three JS.

**Topics covered**

Web GL 
Open GL
Three Js
React Three Fiber
        
**Expected Duration**

15-20 min.

**Track**

- [X] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**

        
**Resources**

**Content**

    
---
### Note
The time and venue will be decided in the Discord group, so make sure you've joined up the group.

**Comment by king-11** [comment]
Add in the resources if possible then we can close the issue

**Comment by Anikaaasingh** [comment]
[Purple and Black Simple Technology Keynote Presentation (2).pdf](https://github.com/COPS-IITBHU/DevTalks/files/10168748/Purple.and.Black.Simple.Technology.Keynote.Presentation.2.pdf)
