### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by bhaskar0120** [COPS-IITBHU/DevTalks#31]
**Abstract**

An introduction to functional programming paradigm.

**Topics covered**

- What is functional programming?
- Basic of functional programming?
- What thought process goes behind solving a problem a functionally?
- Some problem solving.
- Basic AMA session.
        
**Expected Duration**

15 - 20 mins

**Track**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**

None
        
**Resources**

- [99 Problems in lisp](https://www.ic.unicamp.br/~meidanis/courses/mc336/problemas-lisp/L-99_Ninety-Nine_Lisp_Problems.html)
- [Lisp](https://www.sbcl.org)
- [Elixir](https://elixir-lang.org/)
- [Haskell](https://www.haskell.org/)
- [Recursion Problems](https://leetcode.com/problemset/all/?topicSlugs=recursion&page=1)

**Content**

    
---
### Note
The time and venue will be decided in the Discord group, so make sure you've joined up the group.

**Comment by king-11** [comment]
Closing it i actually forgot the date do you remember?
