### ISSUE TITLE
AR portal in websites

### ISSUE THREAD

**Issue by yashrajbharti** [COPS-IITBHU/DevTalks#5]
**Abstract**
Going to tell about AR website and will create one during the course of the devtalk

**Topics covered**
Front end web dev, AR+, WebAR       
**Expected Duration**
45mins
**Track**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Prerequisites**
knowledge of basic frontend web dev
        
**Resources**
will put that later

**Content**
Augmented reality is the system that fulfills three basic features: a combination of real and virtual worlds, real-time interaction, and accurate 3D registration of virtual and real objects. WebAR is an emerging tech that will help us dive deep into both the how limitless frontend is, and how real can AR+ portals get. 
    
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by shivanshs9** [comment]
Held on 10/11/2019 :raised_hands:
