### ISSUE TITLE
Client-side Machine learning

### ISSUE THREAD

**Issue by BAJUKA** [COPS-IITBHU/DevTalks#7]
**Abstract**
The talk is going to be about client side machine learning. The talk will highlight why it is beneficial to deploy AI on the client side and also some limitations. The talk will conclude with a discussion on TensorFlow.js which is a tool that can be used for client side deployment of AI.

**Topics covered**
- Client side machine learning
- TensorFlow.js

**Expected Duration**
45 mins

**Track**

- [x] Beginner
- [ ] Intermediate
- [ ] Advanced

**Prerequisites**
None but a little idea of JavaScript would be helpful
        
**Resources**
https://www.tensorflow.org/js

**Content**

---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by shivanshs9** [comment]
Held on 10/11/2019 :raised_hands:
