### ISSUE TITLE
WebAR with 8th Wall and 8i

### ISSUE THREAD

**Issue by yashrajbharti** [COPS-IITBHU/DevTalks#8]
**Abstract**
Going to make webAR experience using 8i , 8thframe

**Topics covered**
WebAR, WebXR (extended reality)
        
**Expected Duration**
less than 25 minutes

**Track**

- [ ] Beginner
- [x] Intermediate
- [ ] Advanced

**Prerequisites**
 No prerequisites 
        
**Resources**

    [8th](https://www.8thwall.com) 

**Content**
 
https://github.com/8thwall/web
---

**Comment by nishantwrp** [comment]
Held on 5 Sept, 2020.

Slides -> https://drive.google.com/file/d/1snj_Gxr73MEfXZP__wTB1mojQcJk23Gy/view?usp=sharing
