### ISSUE TITLE
Advanced Git

### ISSUE THREAD

**Issue by king-11** [COPS-IITBHU/DevTalks#9]
**Abstract**
Git is a really powerful tool for version control, but most of the users only use a fixed set of commands which don't allow them to use git's full potential, and we find ourselves in tight places where we have no idea how to resolve some issue. In this talk, I will be focusing on some new tools, better workflow, and insight into Git's working

**Topics covered**
- stashing and cherry picking
- branches, rebasing and merging
- better commits and workflow for git
        
**Expected Duration**
1 hr

**Track**
- [x] Advanced

**Prerequisites**
Familiarity with basic git commands will develop over them.
        
**Resources**
Article and related courses will be provided.

**Content**
Ppt will we shared
    
---
### Note
The time and venue will be decided in the Telegram group, so make sure you've joined up the group.

**Comment by nishantwrp** [comment]
Talk was given on 5 Sept, 2020.

Slides -> https://www.canva.com/design/DAEGzoLlbB8/T-jbcRqJXZ62ZKJzundghA/view#1
